name = "theme"
license = "MIT"
licenselink = "https://github.com/d4sein/my-hugo-theme/blob/master/LICENSE"
description = "A simple and concise Hugo theme"
homepage = "https://github.com/d4sein/my-hugo-theme"
tags = ["blog", "simple", "clean", "highlight", "readable"]
features = ["blog", "simple", "clean", "highlight"]
min_version = "0.53"

[author]
  name = "Willian Nascimento"
  homepage = "https://d4sein.github.io/"
  repo = "https://github.com/d4sein/my-hugo-theme"

[original.author]
  name = "Rainer Chiang"
  homepage = "https://rainerchiang.github.io/"
  repo = "https://github.com/RainerChiang/simpleness"
